# netlify.toml (Frontend only; publish = dist)

[build]
  command = "npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, must-revalidate"
