# netlify.toml (clean, single [build] block)

[build]
  command = "bash ./netlify-build.sh"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  # Ensure Netlify provisions Python 3.11 (via mise)
  PYTHON_VERSION = "3.11"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"
  PIP_NO_INPUT = "1"
  # If you want Node Playwright browsers during build, set this to "1" in Netlify UI
  USE_NODE_PLAYWRIGHT = "0"
  # If you want Python Playwright browsers during build, set this to "1" in Netlify UI
  USE_PY_PLAYWRIGHT = "0"

# Optional: give Netlify a hint for Python functions runtime (if you add any Python functions)
[functions."*"]
  included_files = ["requirements.txt", "constraints.txt"]
